version: '3'
services:
  FlaskApiTest-service:
    image: "flask-api:v1.0.0"
    command: sh /var/www/flask-api-tutorial-master/flask_setup.sh
    container_name: FlaskApiTest-service
    # networks:
    #   - devnet
    volumes:
      - ./flask_setup.sh:/var/www/flask-api-tutorial-master/flask_setup.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/_status"]
      interval: 60s
      timeout: 5s
      retries: 3
    environment:
      - PYTHONPATH=/var/www/flask-api-tutorial-master/
#      - GEN3_DEBUG=True
    ports:
      - 8081:5000